# permissions for end users to view canarydeploys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: canarydeploy-viewer-role
rules:
- apiGroups:
  - cloudship.toucansoft.io.toucansoft.io
  resources:
  - canarydeploys
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloudship.toucansoft.io.toucansoft.io
  resources:
  - canarydeploys/status
  verbs:
  - get
